/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WalletIdRouteImport } from './routes/wallet.$id'
import { Route as DebugProfileSearchRouteImport } from './routes/debug/profile-search'

const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletIdRoute = WalletIdRouteImport.update({
  id: '/wallet/$id',
  path: '/wallet/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugProfileSearchRoute = DebugProfileSearchRouteImport.update({
  id: '/debug/profile-search',
  path: '/debug/profile-search',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/debug/profile-search': typeof DebugProfileSearchRoute
  '/wallet/$id': typeof WalletIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/debug/profile-search': typeof DebugProfileSearchRoute
  '/wallet/$id': typeof WalletIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/debug/profile-search': typeof DebugProfileSearchRoute
  '/wallet/$id': typeof WalletIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/leaderboard' | '/debug/profile-search' | '/wallet/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/leaderboard' | '/debug/profile-search' | '/wallet/$id'
  id:
    | '__root__'
    | '/'
    | '/leaderboard'
    | '/debug/profile-search'
    | '/wallet/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeaderboardRoute: typeof LeaderboardRoute
  DebugProfileSearchRoute: typeof DebugProfileSearchRoute
  WalletIdRoute: typeof WalletIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/$id': {
      id: '/wallet/$id'
      path: '/wallet/$id'
      fullPath: '/wallet/$id'
      preLoaderRoute: typeof WalletIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/profile-search': {
      id: '/debug/profile-search'
      path: '/debug/profile-search'
      fullPath: '/debug/profile-search'
      preLoaderRoute: typeof DebugProfileSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeaderboardRoute: LeaderboardRoute,
  DebugProfileSearchRoute: DebugProfileSearchRoute,
  WalletIdRoute: WalletIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
